---
apiVersion: v1
kind: ConfigMap
metadata:
  name: yelp-camp-config
data:
  CLOUDINARY_CLOUD_NAME: "do9hz0869"
  CLOUDINARY_KEY: "478666985338558"
  CLOUDINARY_SECRET: "scHMMSCZsnEJDTTY9SckFOftkIs"
  MAPBOX_TOKEN: "pk.eyJ1IjoiYXdhaXM2ODQwIiwiYSI6ImNtb2F6OHphbzBhd2QycHNod3VwM3l3Z3oifQ.4xJlItigc0cLU9FxQobDAg"
  DB_URL: "mongodb+srv://awais684:Pu.y5YWTg5WfnxQ@cluster1.lvahez6.mongodb.net/?appName=Cluster1"
  SECRET: "awais"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: yelp-camp-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: yelp-camp
  template:
    metadata:
      labels:
        app: yelp-camp
    spec:
      containers:
        - name: yelp-camp-container
          image: awais684/camp:latest

          ports:
            - containerPort: 3000

          envFrom:
            - configMapRef:
                name: yelp-camp-config

          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 30
            periodSeconds: 10

          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 30
            periodSeconds: 10

---
apiVersion: v1
kind: Service
metadata:
  name: yelp-camp-service
spec:
  selector:
    app: yelp-camp
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
